### ISSUE TITLE
Sidebar is not clickable if it set to Right Side

### ISSUE THREAD

**Issue by kandiva** [MarcBruins/MvvmCross-Sidebar-Sample#1]
Sidebar items are not clickable if the panel is set to the "Right Side" and try to swipe. If it is set to left side, it works fine.

**Comment by MarcBruins** [comment]
Updated the ios support package, this should fix it.

**Comment by PrasadKurdiMatta** [comment]
Hi @MarcBruins,

When i changed RightSideBar like below in file MvxSidebarPanelController.cs

RightSidebarController = new SidebarController(this, NavigationController, initialEmptySideMenu);

I was able to get my code working.

Thanks
Prasad

**Comment by MarcBruins** [comment]
Closed
